#' Example sentence in CONLL format
#'
#' An example sentence in CONLL format
#'
#' @format A data frame with 13 rows and 9 variables:
#' \describe{
#'   \item{SENTID}{sentence id}
#'   \item{TOKEN}{token}
#'   \item{POS.TT}{part of speech generated by treetagger}
#'   \item{LEMMA}{lemma}
#'   \item{POS.MELT}{part of speech generated by MElt}
#'   \item{DESC}{extra part of speech information (i.e. morpholgical tags)}
#'   \item{POSITION}{position in the sentence}
#'   \item{DEP_TYPE}{type of dependency relation}
#'   \item{DEP_ON}{head of dependency}
#' }

"example"
