# Copyright (c) 2021 Centre for English Corpus Linguistics, Université catholique de Louvain
# Author: Nathan Vandeweerd
# Contact: cecl@uclouvain.be
#
# This package is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or any later version. This  program
# is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details. When using this package
# please include the following citation:
#
#   > Vandeweerd N (in press). *fsca: French syntactic complexity analyzer.* International Journal of Learner Corpus Research.
#
# You should have received a copy of the GNU General Public License along with
# this package. If not, see <http://www.gnu.org/licenses/>.



#' Example sentence in CONLL format
#'
#' An data frame which contains an example sentence in CONLL format
#' @usage data(example)
#'
#' @format A data frame containing 13 rows and 9 columns. The columns are as follows:
#' \describe{
#'   \item{SENTID}{sentence id}
#'   \item{TOKEN}{token}
#'   \item{POS.TT}{part of speech generated by treetagger}
#'   \item{LEMMA}{lemma}
#'   \item{POS.MELT}{part of speech generated by MElt}
#'   \item{DESC}{extra part of speech information (i.e. morpholgical tags)}
#'   \item{POSITION}{position in the sentence}
#'   \item{DEP_TYPE}{type of dependency relation}
#'   \item{DEP_ON}{head of dependency}
#' }

"example"


#' Example sentences in CONLL format
#'
#' An list of example sentences in CONLL format
#' @usage data(test.sents)
#'
#' @format A list containing 11 data frames. Each data frame has the following columns:
#' \describe{
#'   \item{SENTID}{sentence id}
#'   \item{TOKEN}{token}
#'   \item{POS.TT}{part of speech generated by treetagger}
#'   \item{LEMMA}{lemma}
#'   \item{POS.MELT}{part of speech generated by MElt}
#'   \item{DESC}{extra part of speech information (i.e. morpholgical tags)}
#'   \item{POSITION}{position in the sentence}
#'   \item{DEP_TYPE}{type of dependency relation}
#'   \item{DEP_ON}{head of dependency}
#' }

"test.sents"
