#' Example sentence in CONLL format
#'
#' An data frame which contains an example sentence in CONLL format
#' @usage data(example)
#'
#' @format A data frame containing 13 rows and 9 columns. The columns are as follows:
#' \describe{
#'   \item{SENTID}{sentence id}
#'   \item{TOKEN}{token}
#'   \item{POS.TT}{part of speech generated by treetagger}
#'   \item{LEMMA}{lemma}
#'   \item{POS.MELT}{part of speech generated by MElt}
#'   \item{DESC}{extra part of speech information (i.e. morpholgical tags)}
#'   \item{POSITION}{position in the sentence}
#'   \item{DEP_TYPE}{type of dependency relation}
#'   \item{DEP_ON}{head of dependency}
#' }

"example"


#' Example sentences in CONLL format
#'
#' An list of example sentences in CONLL format
#' @usage data(test.sents)
#'
#' @format A list containing 11 data frames. Each data frame has the following columns:
#' \describe{
#'   \item{SENTID}{sentence id}
#'   \item{TOKEN}{token}
#'   \item{POS.TT}{part of speech generated by treetagger}
#'   \item{LEMMA}{lemma}
#'   \item{POS.MELT}{part of speech generated by MElt}
#'   \item{DESC}{extra part of speech information (i.e. morpholgical tags)}
#'   \item{POSITION}{position in the sentence}
#'   \item{DEP_TYPE}{type of dependency relation}
#'   \item{DEP_ON}{head of dependency}
#' }

"test.sents"
